name: "Build with Nix and cache with Cachix"

on:
  workflow_call:
    inputs:
      oses:
        description: 'JSON array of GitHub runner labels to build on'
        required: false
        type: string
        default: '["ubuntu-latest","macos-latest"]'
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: Build & Cache (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.oses) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Linux: multi-user install with KVM enabled
      - name: Install Nix (Linux)
        if: runner.os == 'Linux'
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          enable_kvm: true

      # macOS: Determinate Systems installer (multi-user, idempotent)
      - name: Install Nix (macOS)
        if: runner.os == 'macOS'
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: dmlane
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: ''
          skipPush: true

      # Build and push all outputs to Cachix
      - name: Build and push to Cachix
        id: build
        run: |
          nix build --no-link --json .#default |
            jq -r '.[].outputs.out' |
            tee outputs.txt

          while read -r out; do
            echo "Built output: $out"
            ls -la "$out"
            cachix push dmlane --omit-deriver "$out"
          done < outputs.txt

          echo "outputs=$(paste -sd ' ' outputs.txt)" >> "$GITHUB_OUTPUT"

      - name: Pin latest build to Cachix
        run: |
          PROJECT_NAME=$(basename "$GITHUB_REPOSITORY")
          OS_NAME="${{ matrix.os }}"
          case "$OS_NAME" in
            ubuntu-*)   ARCH_SUFFIX=linux ;;
            macos-*)    ARCH_SUFFIX=darwin ;;
            *)          ARCH_SUFFIX=unknown ;;
          esac
          OUTPUT_PATH="${{ steps.build.outputs.outputs }}"
          PIN_NAME="${PROJECT_NAME}-${ARCH_SUFFIX}"
          echo "Pinning $PIN_NAME -> $OUTPUT_PATH"
          cachix pin dmlane "$PIN_NAME" "$OUTPUT_PATH" --keep-revisions 5
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

